service: toe-api

package:
  exclude:
    - tests/**
    - logs/**
    - resource/**
    - node_modules/**
    - .env*
  include:
    - ../.docker/mysql/data/**
provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  runtime: provided
  iamManagedPolicies:
    - 'arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
    - 'arn:aws:iam::aws:policy/AmazonRDSDataFullAccess'
  iamRoleStatements:
    - Effect: Allow
      Action:
        - ses:*
      Resource: "*"
    - Effect: Allow
      Action:
        - s3:*
      Resource: ${cf:${self:custom.PERSIST_STACK_NAME}-${self:provider.stage}.AppS3RouteBucketArn}
    - Effect: Allow
      Resource: '*'
      Action:
        - rds-data:ExecuteStatement
        - rds-data:BeginTransaction
        - rds-data:CommitTransaction
        - rds-data:RollbackTransaction
    - Effect: Allow
      Resource: ${self:custom.TOE_SERVERLESS_DB.SECRET_ARN}
      Action:
        - secretsmanager:GetSecretValue
  environment:
    TOE_DONT_USE_DOTENV: true
    TOE_STAGE: ${self:provider.stage}
    # Uncomment the TOE_DATABASE_* env vars because they are only applicable for non-aurora serverless databases
#    TOE_DATABASE_HOST: ${self:custom.TOE_DATABASE.HOST}
#    TOE_DATABASE_PORT: ${self:custom.TOE_DATABASE.PORT}
#    TOE_DATABASE_USER: ${self:custom.TOE_DATABASE.USER}
#    TOE_DATABASE_PASSWORD: ${self:custom.TOE_DATABASE.PASSWORD}
    TOE_ENCODED_JWT_KEY: ${self:custom.TOE_JWT}
    TOE_LOGGING_LEVEL: ${self:custom.TOE_LOGGING_LEVEL}
    TOE_LOG_FILE: ${self:custom.TOE_LOG_FILE}
    TOE_ACCESS_CONTROL_ALLOW_ORIGIN: ${self:custom.TOE_ACCESS_CONTROL_ALLOW_ORIGIN}
    TOE_RESET_ACCOUNT_EMAIL: ${self:custom.TOE_PASSWORD_RESET.EMAIL}
    TOE_RESET_CLIENT_ID: ${self:custom.TOE_PASSWORD_RESET.GCP_CLIENT_ID}
    TOE_RESET_CLIENT_SECRET: ${self:custom.TOE_PASSWORD_RESET.GCP_CLIENT_SECRET}
    TOE_RESET_REFRESH_TOKEN: ${self:custom.TOE_PASSWORD_RESET.GCP_REFRESH_TOKEN}
    TOE_AWS_REGION: ${self:custom.TOE_AWS_REGION}
    TOE_S3_ROUTE_BUCKET: ${self:custom.TOE_S3_ROUTE_BUCKET}
    TOE_DB_ARN: ${self:custom.TOE_SERVERLESS_DB.ARN}
    TOE_DB_SECRET_ARN: ${self:custom.TOE_SERVERLESS_DB.SECRET_ARN}
    TOE_EMAIL_CLIENT: ses
    TOE_OBJECT_STORAGE_TYPE: s3
    TOE_DATABASE_TYPE: aurora
custom:
  PERSIST_STACK_NAME: toe-api-data-persistence
  TOE_DATABASE:
    HOST: ${cf:${self:custom.PERSIST_STACK_NAME}-${self:provider.stage}.AppDBHost}
    PORT: ${cf:${self:custom.PERSIST_STACK_NAME}-${self:provider.stage}.AppDBPort}
    USER: ${cf:${self:custom.PERSIST_STACK_NAME}-${self:provider.stage}.AppDBUsername}
    PASSWORD: ${cf:${self:custom.PERSIST_STACK_NAME}-${self:provider.stage}.AppDBPassword}
  TOE_SERVERLESS_DB:
    ARN: ${cf:${self:custom.PERSIST_STACK_NAME}-${self:provider.stage}.AppDBArn}
    SECRET_ARN: ${file(./account_config.yaml):DBSecretARN}
  TOE_DATABASE_SG: ${cf:${self:custom.PERSIST_STACK_NAME}-${self:provider.stage}.AppDBSecurityGroupId}
  TOE_JWT: ${ssm:/toe/prod/TOE_ENCODED_JWT_KEY}
  TOE_LOGGING_LEVEL: 'INFO' #normally set to INFO
  TOE_LOG_FILE: 'php://stdout' # this will send log output to stdout and be picked up by cloudwatch
  TOE_ACCESS_CONTROL_ALLOW_ORIGIN: ${ssm:/toe/prod/ClientDomain}
  TOE_AWS_REGION: ${self:provider.region}
  TOE_PASSWORD_RESET:
    EMAIL: ${ssm:/toe/prod/PASSWORD_RESET_EMAIL}
    GCP_CLIENT_ID: ${ssm:/toe/prod/GCP_CLIENT_ID}
    GCP_CLIENT_SECRET: ${ssm:/toe/prod/GCP_CLIENT_SECRET}
    GCP_REFRESH_TOKEN: ${ssm:/toe/prod/GCP_CLIENT_REFRESH}
  TOE_S3_ROUTE_BUCKET: ${cf:${self:custom.PERSIST_STACK_NAME}-${self:provider.stage}.AppS3RouteBucketName}
  customDomain:
    domainName: ${file(./account_config.yaml):APIDomain}
    basePath: ''
    stage: ${self:provider.stage}
    createRoute53Record: true

plugins:
  - ./vendor/bref/bref
  - serverless-domain-manager
resources:
  Resources:
    CloudfrontOAI:
      Type: 'AWS::CloudFront::CloudFrontOriginAccessIdentity'
      Properties:
        CloudFrontOriginAccessIdentityConfig:
          Comment: static content for TOE
    WebsiteCDN:
      Type: 'AWS::CloudFront::Distribution'
      Properties:
        DistributionConfig:
          Origins:
          - DomainName: !Join ['.', ['${ssm:/toe/prod/CFBucketName}', 's3.amazonaws.com'] ]
            Id: ToeS3Origin
            S3OriginConfig:
              OriginAccessIdentity: !Join ['/', ['origin-access-identity/cloudfront', !Ref CloudfrontOAI ] ]
          Enabled: 'true'
          Comment: 'Trick or eat distribution'
          DefaultRootObject: index.html
          Aliases:
            - www.guelphtrickoreat.ca
            - guelphtrickoreat.ca
          DefaultCacheBehavior:
            AllowedMethods:
              - GET
              - HEAD
              - OPTIONS
            TargetOriginId: ToeS3Origin
            ForwardedValues:
              QueryString: 'false'
              Cookies:
                Forward: none
            ViewerProtocolPolicy: redirect-to-https
          PriceClass: PriceClass_100
          Restrictions:
            GeoRestriction:
              RestrictionType: whitelist
              Locations:
                - CA
                - US
                - AU # Australia
                - BE # Belgium
                - DK # Denmark
                - DE # Germany
                - IE # Ireland
                - IL # Israel
                - NZ # New Zealand
                - NL # Netherlands
                - CH # Switzerland
                - IO # British Indian Ocean Territory
                - IT # Italy
                - JP # Japan
                - MY # Malaysia
          ViewerCertificate:
            MinimumProtocolVersion: TLSv1.1_2016
            SslSupportMethod: sni-only
            AcmCertificateArn: ${file(./account_config.yaml):ACMCertificateArn}
      DependsOn:
        - CloudfrontOAI
    WebsiteDNSRecord:
      Type: 'AWS::Route53::RecordSet'
      Properties:
        HostedZoneName: !Join ['', [ '${ssm:/toe/prod/BaseDomain}', '.' ] ]
        AliasTarget:
          DNSName: !GetAtt WebsiteCDN.DomainName
          HostedZoneId: Z2FDTNDATAQYW2
        Name: guelphtrickoreat.ca.
        Type: A
      DependsOn:
        - WebsiteCDN
    CFBucketPolicyS3:
      Type: 'AWS::S3::BucketPolicy'
      Properties:
        Bucket: guelphtrickoreat.ca
        PolicyDocument:
          Version: '2008-10-17'
          Id: PolicyForTOECloudFrontPrivateContent
          Statement:
            - Sid: '1'
              Effect: Allow
              Principal:
                AWS: !Join [' ', ['arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity', !Ref CloudfrontOAI ] ]
              Action: s3:GetObject
              Resource: !Join ['', ['arn:aws:s3:::', '${ssm:/toe/prod/CFBucketName}', '/*' ] ]
      DependsOn:
        - CloudfrontOAI

functions:
  api:
    handler: public/index.php
    description: 'The entire trick-or-eat api backend'
    timeout: 30 # in seconds (API Gateway has a timeout of 30 seconds)
    layers:
      - ${bref:layer.php-72-fpm}
    events:
      - http:
         path: '/'
         method: 'ANY'
         cors:
           origins:
             - '${ssm:/toe/prod/ClientDomain}'
           headers:
             - Content-Type
             - Accept-Encoding
             - X-Bearer-Token
           allowCredentials: true
      - http:
         path: '/{proxy+}'
         method: 'ANY'
         cors:
           origins:
             - '${ssm:/toe/prod/ClientDomain}'
           headers:
             - Content-Type
             - Accept-Encoding
             - X-Bearer-Token
           allowCredentials: true
  cron:
    handler: bin/console.php
    timeout: 30
    layers:
      - ${bref:layer.php-72}
      - ${bref:layer.console}
    events:
      - schedule:
          name: clean-reset-tokens
          description: clears the most resent password reset tokens from the database
          rate: cron(45 0 1 * ? *) # For the demo, only needs to run once a month. Should be changed to every hour in prod
          input:
            cli: clean-reset-tokens

## In order to print out the hosted domain via `serverless info` we need to define the DomainName output for CloudFormation
Outputs:
#  WebsiteCDNOutput:
#    Value:
#      Fn::GetAtt: [ WebsiteCDN, DomainName ]
#  AppDBName:
#    Value: !Ref AppDB
#  AppDBHost:
#    Value: !GetAtt AppDB.Endpoint.Address
#  AppDBPort:
#    Value: !GetAtt AppDB.Endpoint.Port
#  AppDBSecurityGroup:
#    Value: !GetAtt AppDBSecurity.GroupId

# on the hooks, use aws:deploy:finalize:cleanup
